version: '3.2'

networks :
  my_network:
    driver: bridge

volumes:
  backend:
    driver: local
    name: volume_backend

services:
  gateway:
    image: nginx
    container_name: gateway
    volumes:
      - ./.conf/nginx/conf:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend
    expose:
      - 8000
    volumes:
      - backend:/app/media
    networks:
      - my_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my_frontend
    expose:
      - 8000
    networks:
      - my_network
